### ISSUE TITLE
Failure (error.something). when playing with qgroups.

### ISSUE THREAD

**Issue by rubdos** [openSUSE/snapper#296]
Hi!

Chances are high that I'm doing something wrong, but I'm trying to [space-limit snapper using qgroups](http://snapper.io/2016/05/18/space-aware-cleanup.html).

GDB output of snapperd (without symbols. I can try to get the symbols if you want) when running `snapper cleanup number`.
```
[Switching to Thread 0x7ffff405b700 (LWP 6955)]

Thread 2 "snapperd" hit Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x7fffec001a50, 
    tinfo=0x7ffff7dd31a8 <typeinfo for snapper::runtime_error_with_errno>, 
    dest=0x7ffff7b6a340 <snapper::runtime_error_with_errno::~runtime_error_with_errno()>)
    at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:62
62	/build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
(gdb) bt
#0  __cxxabiv1::__cxa_throw (obj=0x7fffec001a50, tinfo=0x7ffff7dd31a8 <typeinfo for snapper::runtime_error_with_errno>, 
    dest=0x7ffff7b6a340 <snapper::runtime_error_with_errno::~runtime_error_with_errno()>)
    at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:62
#1  0x00007ffff7b9a95b in snapper::BtrfsUtils::qgroup_assign(int, unsigned long, unsigned long) () from /usr/lib/libsnapper.so.3
#2  0x00007ffff7b4789d in snapper::Snapper::prepareQuota() const () from /usr/lib/libsnapper.so.3
```

My qgroups setup:

```
2/100       208.43GiB     71.18MiB         none     50.00GiB 3/0         
2/200        97.56GiB      2.36GiB         none     10.00GiB 3/0         
3/0         210.90GiB      2.49GiB    400.00GiB         none ---
```

I use 2/100 for my `/home` snapshots, and 2/200 for my `/` snapshots. It could be that I don't really understand it well though. 3/0 is just a global limit so that I don't get to more than 90% usage on my btrfs partition.

**Comment by rubdos** [comment]
Seemed like I just had a bad config file for my root. Sorry to bother you :)
