### ISSUE TITLE
FileUtils.cc(SDir):88 - THROW: open failed path:/home/.snapshots errno:2 (No such file or directory)

### ISSUE THREAD

**Issue by muradm** [openSUSE/snapper#449]
Similar error was reported long ago in #224 and #303 with reference that should be fixed in newer versions. This one from latest 0.8.0 published in ArchLinux repository.

```
$ more /etc/fstab | grep home
LABEL=system        	/home     	btrfs     	rw,noatime,ssd,space_cache,subvolid=258,subvol=/home,subvol=home	0 0
LABEL=system		/home/.snapshots	btrfs	rw,noatime,ssd,space_cache,subvolid=270,subvol=/home-snapshots,subvol=home-snapshots	0 0
$ ls -la /home/.snapshots
total 0
drwxr-xr-x 1 root root  2 Nov  3 13:23 .
drwxr-xr-x 1 root root 32 Oct 22 23:55 ..
drwxr-xr-x 1 root root 32 Nov  3 13:22 2
$ sudo snapper -c home -v list
IO Error (open failed path:/home/.snapshots errno:2 (No such file or directory)).
```

```
2018-11-04 13:31:25 MIL libsnapper(12393) snapperd.cc(main):276 - Requesting DBus name
2018-11-04 13:31:25 MIL libsnapper(12393) snapperd.cc(main):280 - Loading snapper configs
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(getConfigs):272 - Snapper get-configs
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(getConfigs):273 - libsnapper version 0.8.0
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(reload):114 - loading file /etc/conf.d/snapper
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:SNAPPER_CONFIGS value:root home
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(reload):114 - loading file /etc/snapper/configs/root
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:SUBVOLUME value:/
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(reload):114 - loading file /etc/snapper/configs/home
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:SUBVOLUME value:/home
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:ALLOW_USERS value:
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:ALLOW_GROUPS value:
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:ALLOW_USERS value:
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:ALLOW_GROUPS value:
2018-11-04 13:31:25 MIL libsnapper(12393) snapperd.cc(main):284 - Listening for method calls and signals
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(Snapper):91 - Snapper constructor
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(Snapper):92 - libsnapper version 0.8.0
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(Snapper):93 - config_name:home disable_filters:false
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(reload):114 - loading file /etc/snapper/configs/home
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:SUBVOLUME value:/home
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:FSTYPE value:btrfs
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:QGROUP value:
2018-11-04 13:31:25 MIL libsnapper(12393) AsciiFile.cc(getValue):235 - key:SYNC_ACL value:no
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(Snapper):125 - subvolume:/home filesystem:btrfs
2018-11-04 13:31:25 MIL libsnapper(12393) Snapper.cc(loadIgnorePatterns):177 - number of ignore patterns:8
2018-11-04 13:31:25 MIL libsnapper(12393) Snapshot.cc(read):273 - found 2 snapshots
2018-11-04 13:31:25 WAR libsnapper(12393) FileUtils.cc(SDir):88 - THROW: open failed path:/home/.snapshots errno:2 (No such file or directory)
2018-11-04 13:31:25 WAR libsnapper(12393) Client.cc(dispatch):1824 - CAUGHT: open failed path:/home/.snapshots errno:2 (No such file or directory)
2018-11-04 13:31:55 MIL libsnapper(12393) Snapper.cc(~Snapper):136 - Snapper destructor
```

**Comment by davestechshop** [comment]
This affects me as well. I'm also using 0.8.0 on ArchLinux.

**Comment by chrpinedo** [comment]
I have the same problem in archlinux... I can't delete snapshots

**Comment by gergo-b** [comment]
Same issue here on openSUSE Tumbleweed. `snapper --config home list` fails, however `create` works and also the YaST2 snapper module lists the snapshots without problem.

The issue is already present with 0.7.2. 

Backtrace from a locally built 0.8.0:

> Breakpoint 1, command_get_default_snapshot (conn=..., config_name="home") at commands.cc:307
(gdb) bt
#0  command_get_default_snapshot (conn=..., config_name="home") at commands.cc:307
#1  0x000000000046716b in ProxySnapshotsDbus::getDefault (this=0x4cfc70) at proxy-dbus.cc:112
#2  0x000000000043c96d in list_from_one_config (snapper=0x4cfc40, list_mode=LM_ALL, show_used_space=false) at snapper.cc:453
#3  0x000000000043c4a3 in command_list (snappers=0x7fffffffc0d8) at snapper.cc:438
#4  0x00000000004480fb in main (argc=5, argv=0x7fffffffe1b8) at snapper.cc:1759
(gdb) n
IO Error (open failed path:/home/.snapshots errno:2 (No such file or directory)).
[Inferior 1 (process 11870) exited with code 01]
